test('Esta prueba no puede fallar ', () => {
  
if ( 0 === 1 ) {
  throw new Error("no puede dividir entre cero")
}

})
